Added CHANNEL_ID variable (needs to be set to a value) in config.env.…
ComputerScienceHouse/conditional pull request #360
Opened 2022-08-25 18:48 UTC by atauln

…py, and created a webhook Slack integration that posts to CHANNEL_ID when a major project is submitted (major_project_submission.py)

2022-08-25 18:50 UTC, atauln commented
The config file needs to be editted to add a webhook url pointing to #major-projects/whatever channel you'd like.

2022-08-25 20:55 UTC, atauln commented
Wait I forgor, the CHANNEL_ID variable should actually be a WEBHOOK_URL variable, because the config var needs a webhood url

2022-08-26 16:37 UTC, jabbate19 requested changes
Nit, and pending testing

2022-08-26 16:37 UTC, jabbate19 commented on conditional/blueprints/major_project_submission.py
> +    return requests.post(app.config['WEBHOOK_URL'], json.dumps(payload))
Newline pls :)

2022-08-26 16:37 UTC, jabbate19 commented on conditional/blueprints/major_project_submission.py
> +app.config.from_pyfile(os.path.join(_root_dir, "config.env.py"))
Ignore this was fixed b4 I could post review

2022-08-26 16:41 UTC, atauln commented on conditional/blueprints/major_project_submission.py
> +    return requests.post(app.config['WEBHOOK_URL'], json.dumps(payload))
Is that common practice in coding? Why?

2022-09-04 03:03 UTC, atauln reviewed
Should be good?

2022-09-07 23:51 UTC, atauln commented
Commits Borked

2022-09-07 23:51 UTC, closed without merging